debug = false

[statsd]
endpoint = "127.0.0.1:4000"


[kafka]
host = ["127.0.0.1:9092"]
topic = "test"

[database]

  [database.zhuanqian]
  host = "127.0.0.1"
  port = 3306
  user = "root"
  pass = ""
  db = "ops"

  [database.idfa_check]
  host = "127.0.0.1"
  port = 3306
  user = "root"
  pass = ""
  db = "ops"

[redis]

  [redis.frontend]
  host = "127.0.0.1"
  port = 6379
  pass = ""
  db = 0

  [redis.backend]
  host = "127.0.0.1"
  port = 6379
  pass = ""
  db = 0

  [redis.result]
  host = "127.0.0.1"
  port = 6379
  pass = ""
  db = 0

[advertiser]

  [advertiser.1]
  sharedkey = "c2ad26c6-9d4e-4958-94ca-d8c566ab165a"

  [advertiser.2]
  impl = "jd"

  [advertiser.3]
  impl = "baidu_ime"

  [advertiser.4]
  impl = "qijia"


[amqp]

  [amqp.frontend]
  url = "amqp://guest:guest@127.0.0.1:5672/"
  exchange = "amq.topic"
  routingkey = "*"
